### ISSUE TITLE
langchainrb_rails 0.1.11 is not published on rubygems

### ISSUE THREAD

**Issue by dgmora** [patterns-ai-core/langchainrb_rails#109]
I am getting an error when installing because of `tiktoken_ruby` not being present. Seeing some other github issues, that gem shouldn't be there anymore. I don't get this error when running from `main` however.

I noticed that the latest published version [here](https://rubygems.org/gems/langchainrb_rails) is 0.1.10, not 0.1.11. Maybe it would make sense to publish 0.1.12, since 0.1.11 already has some time?

I am also not 100% sure, but this error I'm getting may also be related with the fact that `Gemfile.lock` is committed _and_ added to the packaged gem. It is being added [here](https://github.com/patterns-ai-core/langchainrb_rails/blob/a08ade3d8291bb940002dd5366d8460a5c0896a2/langchainrb_rails.gemspec#L24-L28). This is different for langchainrb, which doesn't include the Gemfile.lock ([here](https://github.com/patterns-ai-core/langchainrb/blob/main/langchain.gemspec#L23)).

**Comment by andreibondarev** [comment]
@dgmora Oh wow, nice find. I'll publish 0.1.11 and a new 0.1.12 in a bit.

**Comment by andreibondarev** [comment]
@dgmora I went ahead and posted both (missing and new) versions! Lmk if you're having any other issues, questions, etc.
