### ISSUE TITLE
Incompatible with langchainrb HEAD

### ISSUE THREAD

**Issue by emk-klaay** [patterns-ai-core/langchainrb_rails#132]
Currently, this repo requires that langchainrb is < 0.19. This means that it's incompatible with langchainrb HEAD. 

Why is there an upper bound on the lanchainrb version? 

Best, Emil

**Comment by andreibondarev** [comment]
@emk-klaay I think we can drop the upper limit.

**Comment by emk-klaay** [comment]
Closed by https://github.com/patterns-ai-core/langchainrb_rails/pull/131
