### ISSUE TITLE
my llm is ollama, but you add ruby-openai to my Gemfile

### ISSUE THREAD

**Issue by lukefan** [patterns-ai-core/langchainrb_rails#76]
I run this command:
rails generate langchainrb_rails:pgvector --model=Product --llm=ollama
but you add ruby-openai to my Gemfile, and ask me to setup OPENAI_API_KEY

**Comment by andreibondarev** [comment]
@lukefan That seems like a bug then.

**Comment by andreibondarev** [comment]
@lukefan Should be fixed now!
