### ISSUE TITLE
Prompt Template integration

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb_rails#97]
`langchainrb` offers a way to manage prompt templates: https://github.com/patterns-ai-core/langchainrb?tab=readme-ov-file#prompt-templates. It offers a way to save templates to json or yaml files but to a database. Keeping prompts in a database table allows you to modify prompts on the fly and version them if needed.

* Create a generator that creates a `prompts` table and an ActiveRecord model with a simple field to store the prompt template text. Example: https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/vectorsearch/prompts/rag.yaml#L6-L11

**Comment by sergiobayona** [comment]
possible api:

Prompt is an ActiveRecord model.

Creates instance of a prompt:
```Ruby
p = Prompt.new(template: "Tell me a {adjective} joke about {subject}.")
p.save # persist to db
```

Renders prompt template:
```Ruby
p.render({adjective: "funny", subject: "birds"})
# => "Tell me a Funny joke about Birds"
```

Return the template variables:
```Ruby
p.template_variables 
# => ['adjective', 'subject']
```

**Comment by andreibondarev** [comment]
@sergiobayona Makes sense to me!

**Comment by sergiobayona** [comment]
see https://github.com/patterns-ai-core/langchainrb_rails/pull/101
